[build-system]
requires = [
    "setuptools>=68",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "remote-import"
version = "1.0.0"
description = "HTTP remote Python module and package import implementation"
authors = [
    {name = "Leonid Tots"}
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "requests>=2.31.0"
]


[project.urls]
Repository = "https://github.com/huksleva/remote-import"


[tool.setuptools.packages.find]
where = ["src"]
